shellEmulator: true
catalogMode: prefer
cleanupUnusedCatalogs: true
trustPolicy: no-downgrade
packages:
  - ./
  - playground

patchedDependencies:
  entities@7.0.0: patches/entities@7.0.0.patch
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - sharp
