import { ref } from 'vue'

// Stub for useFiles - actual implementation should be provided by consuming project
// This is generated by nitro-graphql codegen in the consuming project
export function useFiles(_page?: number, _limit?: number, _search?: string, _folderId?: string) {
  const data = ref<any>(null)
  const loading = ref(false)
  const error = ref<Error | null>(null)

  return {
    data,
    loading,
    error,
  }
}
